### ISSUE TITLE
Filter timeouted servers from results

### ISSUE THREAD

**Issue by Wibol** [Chizi123/dnscomp#1]
The first DNS servers shown in the list of results are not the fastest ones, but the ones that gave the error "connection timed out; no servers could be reached".

Thanks.

**Comment by Chizi123** [comment]
Hi,

Very happy to do so, although I can't seem to replicate the issue.
Could you attach a tcpdump or the like so I could see what the issue is?
 
Otherwise, I'll try to do some work to exclude invalid responses from being included.

Thanks

**Comment by Wibol** [comment]
I don't know "tcpdump" so I'm going to look for information on how to use it. In the meantime, having the DNS relay of the router disabled:
```
$ dnscomp 
100.00% done
Server               | Time
77.88.88.1           | 0.026922778
23.253.163.53        | 0.026925818
198.101.242.72       | 0.026928384
96.140.14.14         | 0.026929209
149.122.122.122      | 0.026929529
185.220.169.9        | 0.026931205
1.0.0.1              | 0.074677856
1.1.1.1              | 0.078700695
8.8.8.8              | 0.126024252
8.8.4.4              | 0.129272644
156.154.70.1         | 0.158191495
64.6.64.6            | 0.162193896
208.67.222.222       | 0.167609596
208.67.220.220       | 0.174093590
8.26.56.26           | 0.188394552
64.6.65.6            | 0.213331631
156.154.71.2         | 0.222639530
8.20.247.20          | 0.239868384
94.140.15.15         | 0.240584111
185.228.168.9        | 0.241866509
84.200.70.40         | 0.258356439
89.233.43.71         | 0.267598379
84.200.69.80         | 0.268646756
9.9.9.9              | 0.270856723
77.88.8.8            | 0.437828250
91.239.100.100       | 0.955747136
```

All those with times of 0.02xxxxx (6 servers) do not work on my PC and give a timeout error if I check them with the "dig" command:
```
$ dig @198.101.242.72 google.com

; <<>> DiG 9.18.2 <<>> @198.101.242.72 google.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

From 1.0.0.1 onwards they all work for browsing and respond well to the "dig" command. Thank you.

**Comment by Chizi123** [comment]
Just pushed something in commit e330e86abcad7cf60e46a5038ea492a9c5ca0e01
Let me know if that helps

**Comment by Wibol** [comment]
Sorry, I'm not a programmer and I don't know how to test these things. Your "dnscomp-git" package I installed on Manjaro from AUR and I guess I'll have to wait for them to update it there. Thank you very much for your effort and time.

**Comment by Chizi123** [comment]
Oh lol, that's me too.
Try and rebuild the AUR package with `makepkg -si` to rebuild and install the updated version.
The AUR package tracks the git repo, rather than being release based, so running that command whenever there is an update should make the update.

**Comment by Wibol** [comment]
The command you indicate gives the error "==> ERROR: PKGBUILD does not exist.", so I have taken note of the version I had installed (ending in bbcea7c-1), uninstalled it with "pamac", deleted the cache and rebuilt the new version ending in 8f0d56b-1. The problem is still the same.

```
$ dnscomp
100.00% done
Server           | Time        | Errors
23.253.163.53    | 0.026904733 | 0
185.220.169.9    | 0.026908530 | 0
198.101.242.72   | 0.026912919 | 0
149.122.122.122  | 0.026923553 | 0
96.140.14.14     | 0.026937662 | 0
77.88.88.1       | 0.026941756 | 0
1.1.1.1          | 0.067252881 | 0
1.0.0.1          | 0.069099354 | 0
8.8.8.8          | 0.104265615 | 0
8.8.4.4          | 0.113571240 | 0
64.6.64.6        | 0.127594977 | 0
156.154.70.1     | 0.128435268 | 0
89.233.43.71     | 0.140719333 | 0
208.67.222.222   | 0.141403124 | 0
208.67.220.220   | 0.142097658 | 0
91.239.100.100   | 0.160777235 | 0
8.20.247.20      | 0.176704195 | 0
185.228.168.9    | 0.181068233 | 0
8.26.56.26       | 0.187290202 | 0
156.154.71.2     | 0.190539053 | 0
64.6.65.6        | 0.190941120 | 0
94.140.15.15     | 0.201140183 | 0
84.200.70.40     | 0.210832078 | 0
9.9.9.9          | 0.222362290 | 0
84.200.69.80     | 0.237624528 | 0
77.88.8.8        | 0.407277494 | 0
```

README.org says "There is a preloaded list of 20 DNS servers and ..." but the final list includes 26 IPs. Where do those 6 IPs come from that match the number of unresponsive servers?

Some of them seem to be related to others that do work: 185.220.169.9 and 185.228.168.9 or 96.140.14.14 and 94.140.15.15.

Thank you.

Translated with www.DeepL.com/Translator (free version)

**Comment by Chizi123** [comment]
Hey, I think i may have worked out a solution. 
Can you pull and build the icmp branch and let me know if that solves the problem?
You need to run it as root for various reasons to get connection details.

Use `git clone -b icmp https://github.com/Chizi123/dnscomp.git` to clone the branch down and just `make` to build the executable.
After it can be run as `./dnscomp`

**Comment by Wibol** [comment]
Much better, but the first server is still not working: "96.140.14.14 | 0.026930562 | 0" and I can't surf with it. As before, it still has a time of 0.026x.

```
$ git clone -b icmp https://github.com/Chizi123/dnscomp.git
Clonando en 'dnscomp'...
remote: Enumerating objects: 164, done.
remote: Counting objects: 100% (164/164), done.
remote: Compressing objects: 100% (101/101), done.
remote: Total 164 (delta 84), reused 133 (delta 54), pack-reused 0
Recibiendo objetos: 100% (164/164), 59.38 KiB | 1.10 MiB/s, listo.
Resolviendo deltas: 100% (84/84), listo.
$ cd dnscomp/
$ ls
dns.c  dns.h  LICENSE  main.c  Makefile  README.org  servers.h  slist.c  slist.h  test.c
$ make
gcc -Wall -lpthread   -c -o dns.o dns.c
dns.c: En la función ‘reachable’:
dns.c:81:25: aviso: se define la variable ‘icmp_head’ pero no se usa [-Wunused-but-set-variable]
   81 |         struct icmphdr* icmp_head;
      |                         ^~~~~~~~~
gcc -Wall -lpthread   -c -o slist.o slist.c
gcc -Wall -lpthread   -c -o main.o main.c
gcc -o dnscomp dns.o slist.o main.o -Wall -lpthread
$ sudo ./dnscomp
[sudo] contraseña para wibol: 
Testing reachability: 26/26
100.00% done
Server           | Time        | Errors
96.140.14.14     | 0.026930562 | 0
1.1.1.1          | 0.048987308 | 0
89.233.43.71     | 0.055735963 | 0
1.0.0.1          | 0.057888972 | 0
91.239.100.100   | 0.074266232 | 0
8.8.8.8          | 0.093469924 | 0
8.8.4.4          | 0.095744873 | 0
156.154.70.1     | 0.104885727 | 0
64.6.64.6        | 0.106473229 | 0
208.67.220.220   | 0.118370414 | 0
208.67.222.222   | 0.124062827 | 0
185.228.168.9    | 0.163715890 | 0
156.154.71.2     | 0.170117478 | 0
64.6.65.6        | 0.170245752 | 0
84.200.70.40     | 0.180554111 | 0
9.9.9.9          | 0.225214314 | 0
77.88.8.8        | 0.386514907 | 0
The following servers were unreachable:
77.88.88.1
84.200.69.80
8.20.247.20
8.26.56.26
94.140.15.15
23.253.163.53
198.101.242.72
185.220.169.9
149.122.122.122
```
Thanks.

**Comment by Chizi123** [comment]
I think there may be some randomness in the results you're seeing.
If you run it again, you may have that server listed as unreachable.
Currently, I need a response packet 70% of the time to recognize the server as functioning, and I test it 10 times.
I've added in an input argument that allows you to change that number: `-r`.

One of the goals of this project is being able to generate the table relatively quickly, however I see exposing this test number should help with the randomness at the cost of a voluntary slow down.
It should also reduce the number of false negatives being flagged as unreachable.

It'd be great if you could let me know if increasing the number of reachability tests solves the problem.
Otherwise, its future work to confirm that the response received is actually a DNS reply.

**Comment by Wibol** [comment]
I've been testing for several days and I'm confused:

At first I increased the value of -r in steps of 5 until I reached 85 to stop downed servers appearing in the list of results. Then I did the opposite way up to 70 without any down servers appearing again on any occasion.

Can you find an explanation for this? I guess we can consider the issue closed...

Thank you very much for your work. Of all the apps I tried, this one seems to me the best because of its simplicity and efficiency.
